name: "g11n radar"

description: "scan globalization issues in repo"

inputs:
  repoToken:
    description: "Authentication token, use secrets.GITHUB_TOKEN"
    required: true
  skip:
    description: 'comma separated folders, like: abc/,xyz/,foo/'
    required: true

runs:
  using: "docker"
  image: "Dockerfile"